# Generated by Django 3.0.5 on 2020-04-27 08:46

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_auto_20200413_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, max_length=31, verbose_name='phone'),
        ),
    ]
