# Generated by Django 3.0.5 on 2020-05-04 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_auto_20200427_0846'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPhones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('phone', models.CharField(max_length=31)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsableTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=31)),
                ('email', models.CharField(max_length=254)),
                ('tagname', models.CharField(max_length=30)),
            ],
            options={
                'managed': False,
            },
        ),
    ]
