# Generated by Django 3.0.5 on 2020-05-04 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0005_studentphones_usabletable'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='studentphones',
            table='studentphones',
        ),
        migrations.AlterModelTable(
            name='usabletable',
            table='usable_table',
        ),
    ]
