# Generated by Django 3.0.5 on 2020-05-05 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0006_auto_20200504_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='sms_unsub',
            field=models.BooleanField(default=False),
        ),
    ]
