# Generated by Django 3.0.5 on 2020-05-05 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0008_student_sms_unsub'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email_unsub',
            field=models.BooleanField(default=False),
        ),
    ]
