# Generated by Django 3.0.5 on 2020-05-05 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0007_sql_setup'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usabletable',
            table='usabletable',
        ),
    ]
