# Generated by Django 3.0.5 on 2020-05-05 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0010_auto_20200504_2357'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentsPerTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagname', models.CharField(max_length=30)),
                ('count', models.BigIntegerField()),
            ],
            options={
                'db_table': 'studentspertag',
                'managed': False,
            },
        ),
    ]
